apiVersion: v1
kind: Service
metadata:
  name: csi-document-management-service-svc
spec:
  selector:
    app: csi-document-management-service-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
  
